// <auto-generated />
using System;
using ConferenceManagement.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceManagement.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.AgendaItem", b =>
                {
                    b.Property<Guid>("AgendaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("agenda_item_id");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("AgendaItemId")
                        .HasName("pk_agenda_items");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_agenda_items_conference_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_agenda_items_room_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_agenda_items_session_id");

                    b.ToTable("agenda_items", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Conference", b =>
                {
                    b.Property<Guid>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("ConferenceId")
                        .HasName("pk_conferences");

                    b.ToTable("conferences", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.ConferenceRegistration", b =>
                {
                    b.Property<Guid>("ConferenceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conference_registration_id");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ConferenceRegistrationId")
                        .HasName("pk_conference_registrations");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_conference_registrations_conference_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conference_registrations_user_id");

                    b.ToTable("conference_registrations", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("availability_status");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("EquipmentId")
                        .HasName("pk_equipments");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_equipments_session_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.LogisticsTask", b =>
                {
                    b.Property<Guid>("LogisticsTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("logistics_task_id");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("LogisticsTaskId")
                        .HasName("pk_logistics_tasks");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_logistics_tasks_conference_id");

                    b.ToTable("logistics_tasks", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.HasKey("MaterialId")
                        .HasName("pk_materials");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_materials_conference_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_materials_session_id");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ConferenceRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_registration_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("ConferenceRegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_conference_registration_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("QuestionId")
                        .HasName("pk_questions");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_questions_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_questions_user_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RoomId")
                        .HasName("pk_rooms");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("conference_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SessionId")
                        .HasName("pk_sessions");

                    b.HasIndex("ConferenceId")
                        .HasDatabaseName("ix_sessions_conference_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_sessions_room_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.SessionRegistration", b =>
                {
                    b.Property<Guid>("SessionRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_registration_id");

                    b.Property<bool>("IsSpeaker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_speaker");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_status");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SessionRegistrationId")
                        .HasName("pk_session_registrations");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_registrations_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_registrations_user_id");

                    b.ToTable("session_registrations", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ConferenceUser", b =>
                {
                    b.Property<Guid>("OrganizedConferencesConferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("organized_conferences_conference_id");

                    b.Property<Guid>("OrganizersUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizers_user_id");

                    b.HasKey("OrganizedConferencesConferenceId", "OrganizersUserId")
                        .HasName("pk_conference_user");

                    b.HasIndex("OrganizersUserId")
                        .HasDatabaseName("ix_conference_user_organizers_user_id");

                    b.ToTable("conference_user", (string)null);
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.AgendaItem", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", "Conference")
                        .WithMany("AgendaItems")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agenda_items_conferences_conference_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agenda_items_rooms_room_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.Session", "Session")
                        .WithOne("AgendaItem")
                        .HasForeignKey("ConferenceManagement.Domain.Entities.AgendaItem", "SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agenda_items_sessions_session_id");

                    b.Navigation("Conference");

                    b.Navigation("Room");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.ConferenceRegistration", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", "Conference")
                        .WithMany("ConferenceRegistrations")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conference_registrations_conferences_conference_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.User", "User")
                        .WithMany("ConferenceRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conference_registrations_users_user_id");

                    b.Navigation("Conference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Session", "Session")
                        .WithMany("Equipments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_equipments_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.LogisticsTask", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", "Conference")
                        .WithMany("LogisticsTasks")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logistics_tasks_conferences_conference_id");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Material", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", "Conference")
                        .WithMany("Materials")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("fk_materials_conferences_conference_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.Session", "Session")
                        .WithMany("Materials")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_materials_sessions_session_id");

                    b.Navigation("Conference");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.ConferenceRegistration", "ConferenceRegistration")
                        .WithOne("Payment")
                        .HasForeignKey("ConferenceManagement.Domain.Entities.Payment", "ConferenceRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_conference_registrations_conference_registration_id");

                    b.Navigation("ConferenceRegistration");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Question", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Session", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_sessions_session_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Session", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", "Conference")
                        .WithMany("Sessions")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_conferences_conference_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_rooms_room_id");

                    b.Navigation("Conference");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.SessionRegistration", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Session", "Session")
                        .WithMany("SessionRegistrations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_registrations_sessions_session_id");

                    b.HasOne("ConferenceManagement.Domain.Entities.User", "User")
                        .WithMany("SessionRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_registrations_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConferenceUser", b =>
                {
                    b.HasOne("ConferenceManagement.Domain.Entities.Conference", null)
                        .WithMany()
                        .HasForeignKey("OrganizedConferencesConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conference_user_conferences_organized_conferences_conferenc");

                    b.HasOne("ConferenceManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conference_user_users_organizers_user_id");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Conference", b =>
                {
                    b.Navigation("AgendaItems");

                    b.Navigation("ConferenceRegistrations");

                    b.Navigation("LogisticsTasks");

                    b.Navigation("Materials");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.ConferenceRegistration", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.Session", b =>
                {
                    b.Navigation("AgendaItem")
                        .IsRequired();

                    b.Navigation("Equipments");

                    b.Navigation("Materials");

                    b.Navigation("Questions");

                    b.Navigation("SessionRegistrations");
                });

            modelBuilder.Entity("ConferenceManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("ConferenceRegistrations");

                    b.Navigation("Notifications");

                    b.Navigation("Questions");

                    b.Navigation("SessionRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
